// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5256.BlueTapeThree1;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Victor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveVictor1;
    public static SpeedController driveVictor2;
    public static SpeedController driveVictor3;
    public static SpeedController driveVictor4;
    public static RobotDrive driveWPI_Drive;
    public static SpeedController intakeTalonShooter;
    public static SpeedController armTalonArm;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveVictor1 = new Victor(1);
        LiveWindow.addActuator("Drive", "Victor 1", (Victor) driveVictor1);
        
        driveVictor2 = new Victor(2);
        LiveWindow.addActuator("Drive", "Victor 2", (Victor) driveVictor2);
        
        driveVictor3 = new Victor(3);
        LiveWindow.addActuator("Drive", "Victor 3", (Victor) driveVictor3);
        
        driveVictor4 = new Victor(4);
        LiveWindow.addActuator("Drive", "Victor4", (Victor) driveVictor4);
        
        driveWPI_Drive = new RobotDrive(driveVictor4, driveVictor2,
              driveVictor1, driveVictor3);
        
        driveWPI_Drive.setSafetyEnabled(true);
        driveWPI_Drive.setExpiration(0.1);
        driveWPI_Drive.setSensitivity(0.5);
        driveWPI_Drive.setMaxOutput(1.0);
        driveWPI_Drive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveWPI_Drive.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        intakeTalonShooter = new Talon(9);
        LiveWindow.addActuator("Intake", "TalonShooter", (Talon) intakeTalonShooter);
        
        armTalonArm = new Talon(8);
        LiveWindow.addActuator("Arm", "TalonArm", (Talon) armTalonArm);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
